import { getCaptureViews } from '@/lib/capture-ref'
import { UPHOLSTERY_MATERIALS } from '@/stores/configurator-store'

const CATEGORY_DISPLAY: Record<string, string> = {
  fabric: 'Microfibra',
  leather: 'Ecopelle',
}

export async function generatePdf(modelId: string, upholsteryId: string): Promise<void> {
  const captureViews = getCaptureViews()
  if (!captureViews) return

  const { front, side, top, aspectRatio } = await captureViews()
  const { jsPDF } = await import('jspdf')

  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = 297
  const pageH = 210
  const margin = 14

  // ── Header ──
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(8)
  pdf.setTextColor(40, 40, 40)
  pdf.text('IAM', margin, margin)

  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric',
  })
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(7.5)
  pdf.setTextColor(130, 130, 130)
  pdf.text(dateStr, pageW - margin, margin, { align: 'right' })

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(30, 30, 30)
  pdf.text(`${modelId.toUpperCase()} — Configuration Summary`, margin, margin + 7)

  pdf.setDrawColor(210, 210, 210)
  pdf.setLineWidth(0.25)
  pdf.line(margin, margin + 11, pageW - margin, margin + 11)

  // ── Three images ──
  const imgTop = margin + 15
  const imgW = (pageW - margin * 2 - 8) / 3
  const imgH = imgW / aspectRatio
  const imgLabels = ['Front View', 'Side View', 'Top View']
  const imgData = [front, side, top]

  for (let i = 0; i < 3; i++) {
    const x = margin + i * (imgW + 4)
    pdf.addImage(imgData[i], 'JPEG', x, imgTop, imgW, imgH)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(6.5)
    pdf.setTextColor(140, 140, 140)
    pdf.text(imgLabels[i], x + imgW / 2, imgTop + imgH + 4, { align: 'center' })
  }

  // ── Config summary ──
  const summaryTop = imgTop + imgH + 10
  pdf.setDrawColor(210, 210, 210)
  pdf.setLineWidth(0.2)
  pdf.line(margin, summaryTop, pageW - margin, summaryTop)

  const upholstery = UPHOLSTERY_MATERIALS.find(m => m.id === upholsteryId) ?? UPHOLSTERY_MATERIALS[0]
  const colW = (pageW - margin * 2) / 3

  const summaryRows: Array<[string, string]> = [
    ['Upholstery', `${upholstery.name} — ${CATEGORY_DISPLAY[upholstery.category] ?? upholstery.category}`],
    ['Structure Finish', 'Brushed Steel 316'],
  ]

  for (let i = 0; i < summaryRows.length; i++) {
    const [label, value] = summaryRows[i]
    const x = margin + i * colW
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(6.5)
    pdf.setTextColor(150, 150, 150)
    pdf.text(label.toUpperCase(), x, summaryTop + 6)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(9)
    pdf.setTextColor(35, 35, 35)
    pdf.text(value, x, summaryTop + 12)
  }

  // Color swatch under upholstery column
  const swatchY = summaryTop + 16
  const hex = upholstery.colorHex.replace('#', '')
  pdf.setFillColor(
    parseInt(hex.slice(0, 2), 16),
    parseInt(hex.slice(2, 4), 16),
    parseInt(hex.slice(4, 6), 16),
  )
  pdf.setDrawColor(180, 180, 180)
  pdf.setLineWidth(0.2)
  pdf.rect(margin, swatchY, 10, 5, 'FD')
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(7)
  pdf.setTextColor(110, 110, 110)
  pdf.text(`#${hex.toUpperCase()}`, margin + 13, swatchY + 3.5)

  // ── Footer ──
  pdf.setDrawColor(210, 210, 210)
  pdf.setLineWidth(0.2)
  pdf.line(margin, pageH - 10, pageW - margin, pageH - 10)
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(6.5)
  pdf.setTextColor(170, 170, 170)
  pdf.text('Generated by IAM 3D Configurator', margin, pageH - 6)
  pdf.text(dateStr, pageW - margin, pageH - 6, { align: 'right' })

  pdf.save(`iam-${modelId}-${new Date().toISOString().slice(0, 10)}.pdf`)
}
